### ISSUE TITLE
1.6.4 gradle errors

### ISSUE THREAD

**Issue by hummel009** [exaskye/Ears#129]
After an endless number of attempts to revive Forge 1.6.4, I came across this repository, which obviously contains modified and fixed versions that can (in theory) download the missing files. However, I have this error happening.

![image](https://github.com/unascribed/Ears/assets/60618853/7c1dfa07-fe82-4c6f-9620-fb64c705573d)

**Comment by exaskye** [comment]
This specific error is caused by the version of Java you're running Gradle with not having an up-to-date CA database.

I would suggest using [Cracked Polished Blackstone Bricks Voldeloom](https://github.com/CrackedPolishedBlackstoneBricksMC/voldeloom/tree/disaster-time) nowadays rather than trying to resurrect antique ForgeGradle though. Ears' project setup is a little old.

**Comment by hummel009** [comment]
It all worked out for me. Thanks so much for the advice!
