### ISSUE TITLE
Ears and tails won't appear/render

### ISSUE THREAD

**Issue by DeckerExpert** [exaskye/Ears#15]
I have edited my skin to have ears, a tail, and the blue box, and yet it doesn't work
https://imgur.com/a/e9irfdH my skin
https://imgur.com/a/OGk1zKR mod list

**Comment by exaskye** [comment]
You can upload images direct to GitHub; no need for Imgur.

Try without OptiFine, and if it's still busted, try without BetterThirdPerson. Both are just guesses; if you have time (and thankfully you have a small mod list) try removing mods one-by-one to isolate the conflict.

**Comment by DeckerExpert** [comment]
Ok so, I tried removing OptiFine an BetterThirdPerson and its still not working. I have also tried removing mods one-by-one and it still doesn't work; only the Ears mod was present and its still busted.

**Comment by exaskye** [comment]
Hm. Your skin looks fine (I checked this first) and my WIP skin manipulator recognizes it.

**Comment by exaskye** [comment]
What is your in-game username?

**Comment by DeckerExpert** [comment]
HazardousMat

**Comment by exaskye** [comment]
Not getting results trying to look up the UUID and therefore skin...

I see now you have tl_skin_cape in your mods list, which is apparently a TLauncher addon, which means you're probably pirating the game and therefore don't have a Mojang account and haven't uploaded your skin to their servers. I really could not give a shit; Microsoft can die in a fire (she says on Microsoft's git hosting service... I'd be on GitLab if it were viable!), but Ears won't work with alternative skin server patches due to the way it integrates.

If I'm wrong and you've just misspelled your username, let me know. If I'm right, then yeah, I can't fix this.

**Comment by DeckerExpert** [comment]
Ah, I see. I did upload my skin to TLauncher's skin database so I did change it, but I guess TLauncher filters out some of the unused materials in a skin. 
Oh well, its alright. I'm saving money up to actually get a legitimate copy of Minecraft, I'll give an update if it still doesn't work. 
Thank you for your time.

**Comment by exaskye** [comment]
> I guess TLauncher filters out some of the unused materials in a skin.

It's unlikely that's what's wrong; it probably patches in an entirely new skin system that Ears is unaware of. And if I add in explicit support for a pirated skin server I will be catapulted out of the modding scene and potentially roasted over an open court by Microsoft.
