### ISSUE TITLE
Port to 1.5.2 Vanilla to be compatible with Better Than Wolves: Community Edition

### ISSUE THREAD

**Issue by moechakucha** [exaskye/Ears#38]
Mainly want a better skin fix because the one included in BTW:CE is awful.

**Comment by exaskye** [comment]
If BTW:CE already has a skin fix, a vanilla port of Ears for 1.5.2 would probably be incompatible with it. I can make a BTW:CE-specific port.

**Comment by rinOfTheStars** [comment]
An update on what'd be required for this (since it's changed a lot in the last year and a half):

BTW:CE uses a fork of Legacy Fabric for loading addons/other mods as of 2.0.x, so a 1.5.2 Legacy Fabric, BTW:CE-compatible port of Ears would be best off using mixins to just replace the skinfix in BTW:CE when it's present

BTW:CE 3.x is going to be the 1.6.4 forwards-port of the mod, when it eventually comes out (there's quite a bit of work to do iirc, mainly with balancing the new vanilla features and making Loader and toolchain changes so that things work outside of dev environments), so it might be worthwhile to wait until then? Idk

**Comment by rinOfTheStars** [comment]
Been looking into doing a hardfork port of this myself in order to have something available, but I'm coming to the conclusion rn that it might make more sense as something built into CE directly, basically replacing its current skin fix with something based off of Ears. Will probably end up working on the contributions to CE required for that myself, so the question now is: if advice ends up being needed on various implementation details for such a thing, where would it be best to ask for help?

**Comment by rinOfTheStars** [comment]
Made said hardfork; it exists here: https://github.com/BTW-Community/Ears-BTWCE

The hardfork will also be integrated into BTW:CE 3.x directly upon its release—I'll be sure to make sure attribution is provided in any READMEs & the MIT License copy for Ears is already included in the src tree. On that subject, should I also have it as a header on all classes within the project's Ears package?

**Comment by exaskye** [comment]
Cool, thanks. I generally don't have time to maintain the retrofork octopus, so *yet another one* was very much on the backburner. Old versions of vanilla Minecraft have a lot in common, but retroforks tend to have their own forms of deobf and major rearchitecting of the game engine, as they don't have to worry about porting to new versions or playing nice with other mods — as such every Ears retrofork port is its own entire investment into an unfamiliar ecosystem.

NFC has also chosen to integrate Ears rather than have it remain as a separate mod.

I don't particularly care how you display the license. The only note I'll make is for you to keep up easily with future changes to Ears, you should prefer to use ears-common as [a Maven artifact](https://repo.sleeping.town/com/unascribed/ears-common/1.4.6/) or Git submodule rather than copy-pasting the whole thing into your source tree.
