### ISSUE TITLE
Can't get Beta 1.7.3 versions to work

### ISSUE THREAD

**Issue by Aceolu** [exaskye/Ears#96]
I'm unsure if I'm doing something wrong, but I am unable to get neither the vanilla or BTA versions of the 1.7.3 release to work.
Unfortunately, it doesn't result crash, and it leaves me with no logs to post either.

For BTA, using the -javaagent:ears.jar JVM argument method, the console gives me the "Hello from Ears!" message, but the skin
doesn't load any of the ear features ingame, nor does it render the outer skin layer for the body except for the head (Ears
v1.4.6, & BTA1.7.6.2)

Using vanilla b1.7.3, installing the mod via MultiMC's "add to jar" with Ears ver 1.4.6, the same issue is occurring, where the skin
won't load the ear features, or the outer skin layers both with or without the addition of b1.7.3 Modloader

And when trying to do the -javaagent:ears.jar JVM argument outside of BTA, this simply crashes the game before it starts with
this being posted to the console: (It doesn't leave a log file anywhere, so unfortunately, this is all I'm able to share)
[b1.7.3errorlog.txt](https://github.com/unascribed/Ears/files/9165042/b1.7.3errorlog.txt)

I deeply apologize if this is not nearly enough information to work with, but MultiMC is not giving me any kind of logs or errors
to work off of, other than the txt sent above.
I also apologize if I'm missing something glaringly obvious, or for my ignorance in some parts of this process.

**Comment by exaskye** [comment]
Due to a weird limitation, using the Ears agent with b1.7.3 requires you to install a dummy jarmod to delete the META-INF directory. Adding Ears to the jar does not accomplish anything.

The BTA and NFC ports do not work right now as both have received major updates and I haven't yet updated Ears for them.

Beta does not have logs. The console output you sent is its equivalent.
